### ISSUE TITLE
Change to new event

### ISSUE THREAD

**Issue by Pickysaurus** [Pickysaurus/bethesda-archive-check#1]
Check the 'set-plugin-list' event as an option for this check.

**Comment by Pickysaurus** [comment]
https://github.com/Nexus-Mods/extension-plugin-management/blob/5253415234ec8736a7aab0478e1d7d2e642a4018/src/index.ts#L973

**Comment by Pickysaurus** [comment]
Alternate 'plugin-details' list https://github.com/Nexus-Mods/extension-plugin-management/blob/5253415234ec8736a7aab0478e1d7d2e642a4018/src/index.ts#L870

**Comment by IDCs** [comment]
Registered the test to kick off whenever plugins-changed and loot-info-updated events have been emitted.
